version: '3.8'

services:
  database_user:
    build:
      dockerfile: Dockerfile
    container_name: postgres_admin_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      clients_network:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend_user:
    build:
      dockerfile: Dockerfile
    container_name: panel_client_1
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      clients_network:
    ports:
      - "8001:8000"
    depends_on:
      - database
      - app
    restart: always
    stdin_open: true